# 总结

1.  2019年结果不好（且无法选择合适的固定效应）

2.  全样本结果比较好

# 基准回归

-   无论控制年份、省份还是双向固定，结果都比较稳健为负

|              |              |              |              |              |
|--------------|--------------|--------------|--------------|--------------|
|              | \(1\)        | \(2\)        | \(3\)        | \(4\)        |
| VARIABLES    | y            | y            | y            | y            |
|              |              |              |              |              |
| market       | -0.016\*\*\* | -0.018\*\*\* | -0.016\*\*\* | -0.019\*\*   |
|              | (-8.98)      | (-5.82)      | (-7.34)      | (-2.12)      |
| age          | 0.005\*\*\*  | 0.005\*\*\*  | 0.005\*\*\*  | 0.005\*\*\*  |
|              | (22.05)      | (21.65)      | (21.77)      | (21.42)      |
| female       | 0.023\*\*\*  | 0.023\*\*\*  | 0.024\*\*\*  | 0.024\*\*\*  |
|              | (3.62)       | (3.61)       | (3.63)       | (3.63)       |
| edu          | -0.100\*\*\* | -0.100\*\*\* | -0.099\*\*\* | -0.100\*\*\* |
|              | (-22.84)     | (-22.43)     | (-22.22)     | (-22.10)     |
| party        | -0.026\*\*   | -0.026\*\*   | -0.024\*\*   | -0.024\*\*   |
|              | (-2.33)      | (-2.32)      | (-2.13)      | (-2.11)      |
| interstpol   | -0.001       | -0.001       | -0.001       | -0.001       |
|              | (-0.21)      | (-0.25)      | (-0.28)      | (-0.30)      |
| frepol       | -0.002       | -0.001       | -0.002       | -0.001       |
|              | (-0.85)      | (-0.43)      | (-0.92)      | (-0.43)      |
| marriage     | 0.010        | 0.008        | 0.008        | 0.008        |
|              | (1.01)       | (0.88)       | (0.88)       | (0.80)       |
| hukourural   | 0.062\*\*\*  | 0.068\*\*\*  | 0.060\*\*\*  | 0.065\*\*\*  |
|              | (7.49)       | (7.96)       | (7.16)       | (7.53)       |
| sociallevel  | 0.014\*\*\*  | 0.014\*\*\*  | 0.014\*\*\*  | 0.014\*\*\*  |
|              | (7.80)       | (7.24)       | (7.16)       | (6.74)       |
| Constant     | 2.522\*\*\*  | 2.534\*\*\*  | 2.518\*\*\*  | 2.548\*\*\*  |
|              | (98.71)      | (84.94)      | (87.08)      | (34.64)      |
|              |              |              |              |              |
| Observations | 17,294       | 17,294       | 17,294       | 17,294       |
| R-squared    | 0.125        | 0.132        | 0.127        | 0.133        |

t-statistics in parentheses

\*\*\* p\<0.01, \*\* p\<0.05, \* p\<0.1

# 交互项

-   结果不好，两个都不显著

    |               |              |              |
    |---------------|--------------|--------------|
    |               | \(1\)        | \(2\)        |
    | VARIABLES     | y            | y            |
    |               |              |              |
    | market_gini   | -0.020       |              |
    |               | (-1.23)      |              |
    | market        | -0.010       | -0.016       |
    |               | (-0.75)      | (-1.21)      |
    | gini          | 0.062        |              |
    |               | (0.27)       |              |
    | age           | 0.003\*\*\*  | 0.003\*\*\*  |
    |               | (3.83)       | (4.00)       |
    | female        | 0.024\*\*\*  | 0.025\*\*\*  |
    |               | (3.72)       | (3.78)       |
    | edu           | -0.097\*\*\* | -0.097\*\*\* |
    |               | (-21.30)     | (-21.44)     |
    | party         | -0.023\*\*   | -0.023\*\*   |
    |               | (-2.07)      | (-2.05)      |
    | interstpol    | -0.001       | -0.001       |
    |               | (-0.34)      | (-0.28)      |
    | frepol        | -0.002       | -0.002       |
    |               | (-0.68)      | (-0.76)      |
    | marriage      | 0.000        | 0.001        |
    |               | (0.00)       | (0.09)       |
    | hukourural    | 0.064\*\*\*  | 0.064\*\*\*  |
    |               | (7.44)       | (7.37)       |
    | sociallevel   | 0.014\*\*\*  | 0.014\*\*\*  |
    |               | (7.08)       | (6.94)       |
    | market_growth |              | -0.001       |
    |               |              | (-0.86)      |
    | growth        |              | 0.016\*\*    |
    |               |              | (2.40)       |
    | Constant      | 2.634\*\*\*  | 2.533\*\*\*  |
    |               | (16.77)      | (23.65)      |
    |               |              |              |
    | Observations  | 17,166       | 17,294       |
    | R-squared     | 0.136        | 0.137        |

    t-statistics in parentheses

    \*\*\* p\<0.01, \*\* p\<0.05, \* p\<0.1

# 中介三步法

## Gini（负负为正）

|              |              |              |              |
|--------------|--------------|--------------|--------------|
|              | \(1\)        | \(2\)        | \(3\)        |
| VARIABLES    | y            | y            | y            |
|              |              |              |              |
| market       | -0.019\*\*   | -0.010\*\*\* | -0.020\*\*   |
|              | (-2.12)      | (-28.96)     | (-2.15)      |
| gini         |              |              | -0.064       |
|              |              |              | (-0.33)      |
| age          | 0.005\*\*\*  | -0.000       | 0.005\*\*\*  |
|              | (21.42)      | (-1.00)      | (21.43)      |
| female       | 0.024\*\*\*  | 0.000        | 0.023\*\*\*  |
|              | (3.63)       | (1.52)       | (3.60)       |
| edu          | -0.100\*\*\* | -0.000\*     | -0.099\*\*\* |
|              | (-22.10)     | (-1.77)      | (-21.99)     |
| party        | -0.024\*\*   | -0.000       | -0.025\*\*   |
|              | (-2.11)      | (-1.05)      | (-2.18)      |
| interstpol   | -0.001       | -0.000       | -0.002       |
|              | (-0.30)      | (-0.25)      | (-0.36)      |
| frepol       | -0.001       | -0.000\*\*   | -0.001       |
|              | (-0.43)      | (-2.35)      | (-0.34)      |
| marriage     | 0.008        | 0.000        | 0.007        |
|              | (0.80)       | (0.76)       | (0.70)       |
| hukourural   | 0.065\*\*\*  | -0.001\*\*\* | 0.065\*\*\*  |
|              | (7.53)       | (-3.69)      | (7.48)       |
| sociallevel  | 0.014\*\*\*  | 0.000        | 0.014\*\*\*  |
|              | (6.74)       | (0.07)       | (6.88)       |
| Constant     | 2.548\*\*\*  | 0.604\*\*\*  | 2.585\*\*\*  |
|              | (34.64)      | (207.50)     | (18.84)      |
|              |              |              |              |
| Observations | 17,294       | 17,665       | 17,166       |
| R-squared    | 0.133        | 0.984        | 0.133        |

## Growth（正正为正）

|              |              |             |              |
|--------------|--------------|-------------|--------------|
|              | \(1\)        | \(2\)       | \(3\)        |
| VARIABLES    | y            | y           | y            |
|              |              |             |              |
| market       | -0.019\*\*   | 0.400\*\*\* | -0.024\*\*\* |
|              | (-2.12)      | (17.59)     | (-2.59)      |
| growth       |              |             | 0.011\*\*\*  |
|              |              |             | (3.75)       |
| age          | 0.005\*\*\*  | 0.001       | 0.005\*\*\*  |
|              | (21.42)      | (0.97)      | (21.40)      |
| female       | 0.024\*\*\*  | -0.022      | 0.024\*\*\*  |
|              | (3.63)       | (-1.36)     | (3.67)       |
| edu          | -0.100\*\*\* | 0.018       | -0.100\*\*\* |
|              | (-22.10)     | (1.63)      | (-22.15)     |
| party        | -0.024\*\*   | 0.036       | -0.024\*\*   |
|              | (-2.11)      | (1.29)      | (-2.15)      |
| interstpol   | -0.001       | -0.001      | -0.001       |
|              | (-0.30)      | (-0.14)     | (-0.30)      |
| frepol       | -0.001       | 0.002       | -0.001       |
|              | (-0.43)      | (0.37)      | (-0.44)      |
| marriage     | 0.008        | -0.014      | 0.008        |
|              | (0.80)       | (-0.58)     | (0.82)       |
| hukourural   | 0.065\*\*\*  | 0.080\*\*\* | 0.064\*\*\*  |
|              | (7.53)       | (3.75)      | (7.43)       |
| sociallevel  | 0.014\*\*\*  | -0.002      | 0.014\*\*\*  |
|              | (6.74)       | (-0.38)     | (6.75)       |
| Constant     | 2.548\*\*\*  | 6.563\*\*\* | 2.472\*\*\*  |
|              | (34.64)      | (35.88)     | (32.45)      |
|              |              |             |              |
| Observations | 17,294       | 17,800      | 17,294       |
| R-squared    | 0.133        | 0.810       | 0.134        |

# 工具变量

-   数据处理的问题

-   省份层面的问题

# 分维度

-   **政府与市场关系** 非国有经济发展 **产品市场的发育程度** 要素市场的发育程度 **市场中介组织的发育和法律制度环境**

|  |  |  |  |  |  |
|----|----|----|----|----|----|
|  | \(1\) | \(2\) | \(3\) | \(4\) | \(5\) |
| VARIABLES | y | y | y | y | y |
|   |   |   |   |   |   |
| gov_market | -0.022\*\*\* |   |   |   |   |
|   | (-3.82) |   |   |   |   |
| age | 0.005\*\*\* | 0.005\*\*\* | 0.005\*\*\* | 0.005\*\*\* | 0.005\*\*\* |
|   | (21.30) | (21.41) | (21.47) | (21.46) | (21.27) |
| female | 0.024\*\*\* | 0.024\*\*\* | 0.023\*\*\* | 0.023\*\*\* | 0.023\*\*\* |
|   | (3.64) | (3.64) | (3.60) | (3.61) | (3.53) |
| edu | -0.100\*\*\* | -0.099\*\*\* | -0.100\*\*\* | -0.100\*\*\* | -0.100\*\*\* |
|   | (-22.10) | (-22.07) | (-22.13) | (-22.10) | (-22.20) |
| party | -0.024\*\* | -0.024\*\* | -0.024\*\* | -0.024\*\* | -0.024\*\* |
|   | (-2.10) | (-2.09) | (-2.12) | (-2.12) | (-2.15) |
| interstpol | -0.001 | -0.001 | -0.000 | -0.001 | -0.001 |
|   | (-0.30) | (-0.23) | (-0.11) | (-0.30) | (-0.27) |
| frepol | -0.001 | -0.001 | -0.001 | -0.001 | -0.001 |
|   | (-0.34) | (-0.46) | (-0.48) | (-0.43) | (-0.45) |
| marriage | 0.007 | 0.007 | 0.006 | 0.007 | 0.007 |
|   | (0.77) | (0.77) | (0.60) | (0.78) | (0.71) |
| hukourural | 0.065\*\*\* | 0.065\*\*\* | 0.066\*\*\* | 0.065\*\*\* | 0.064\*\*\* |
|   | (7.56) | (7.56) | (7.63) | (7.58) | (7.39) |
| sociallevel | 0.014\*\*\* | 0.014\*\*\* | 0.014\*\*\* | 0.014\*\*\* | 0.014\*\*\* |
|   | (6.76) | (6.73) | (6.69) | (6.71) | (6.80) |
| non_state |   | -0.013\*\*\* |   |   |   |
|   |   | (-2.62) |   |   |   |
| product_market |   |   | 0.029\*\*\* |   |   |
|   |   |   | (6.50) |   |   |
| factor_market |   |   |   | -0.007\*\* |   |
|   |   |   |   | (-2.11) |   |
| market_ins |   |   |   |   | -0.027\*\*\* |
|   |   |   |   |   | (-6.19) |
| Constant | 2.566\*\*\* | 2.514\*\*\* | 2.175\*\*\* | 2.458\*\*\* | 2.585\*\*\* |
|   | (51.30) | (50.34) | (50.87) | (67.02) | (66.62) |
|   |   |   |   |   |   |
| Observations | 17,294 | 17,294 | 17,294 | 17,294 | 17,294 |
| R-squared | 0.134 | 0.133 | 0.135 | 0.133 | 0.135 |

# 数据层级

省份公开

市区县无法实现（村居编码无法还原到市层次）

# 

# 故事的区域扩展：全球

-   WVS的数据处理

-   合并数据（world bank）

-   市场化的测度与冲击